// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables for Supabase credentials
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Add logging to see what values are being read
console.log('DEBUG: VITE_SUPABASE_URL:', SUPABASE_URL);
console.log('DEBUG: VITE_SUPABASE_ANON_KEY:', SUPABASE_ANON_KEY);


// Ensure environment variables are loaded before creating the client
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  // Throw a more specific error if environment variables are missing
  throw new Error("Supabase URL and Anon Key must be set in the .env file. Please check VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
